interface RootObject {
  '0': string;
  '1': string;
  '2': string;
  children: Children;
  attributes: Attributes;
}
interface Attributes {
  '$button-color-prime-primary-shadow': string;
  '$button-color-prime-primary-background': string;
  '$button-color-prime-primary-background-hover': string;
  '$button-color-prime-primary-background-pressed': string;
  '$button-color-prime-primary-border': string;
  '$button-color-prime-primary-border-hover': string;
  '$button-color-prime-primary-border-pressed': string;
  '$button-color-prime-primary-label': string;
  '$button-color-prime-primary-label-hover': string;
  '$button-color-prime-primary-label-pressed': string;
  '$button-color-prime-primary-disabled-label': string;
  '$button-color-prime-primary-disabled-border': string;
  '$button-color-prime-primary-disabled-background': string;
  '$button-color-prime-secondary-shadow': string;
  '$button-color-prime-secondary-background': string;
  '$button-color-prime-secondary-background-hover': string;
  '$button-color-prime-secondary-background-pressed': string;
  '$button-color-prime-secondary-border': string;
  '$button-color-prime-secondary-border-hover': string;
  '$button-color-prime-secondary-border-pressed': string;
  '$button-color-prime-secondary-label': string;
  '$button-color-prime-secondary-label-hover': string;
  '$button-color-prime-secondary-label-pressed': string;
  '$button-color-prime-secondary-disabled-label': string;
  '$button-color-prime-secondary-disabled-border': string;
  '$button-color-prime-secondary-disabled-background': string;
  '$button-color-prime-tertiary-shadow': string;
  '$button-color-prime-tertiary-background': string;
  '$button-color-prime-tertiary-background-hover': string;
  '$button-color-prime-tertiary-background-pressed': string;
  '$button-color-prime-tertiary-border': string;
  '$button-color-prime-tertiary-border-hover': string;
  '$button-color-prime-tertiary-border-pressed': string;
  '$button-color-prime-tertiary-label': string;
  '$button-color-prime-tertiary-label-hover': string;
  '$button-color-prime-tertiary-label-pressed': string;
  '$button-color-prime-tertiary-disabled-label': string;
  '$button-color-prime-tertiary-disabled-border': string;
  '$button-color-prime-tertiary-disabled-background': string;
  '$button-color-muted-primary-shadow': string;
  '$button-color-muted-primary-background': string;
  '$button-color-muted-primary-background-hover': string;
  '$button-color-muted-primary-background-pressed': string;
  '$button-color-muted-primary-border': string;
  '$button-color-muted-primary-border-hover': string;
  '$button-color-muted-primary-border-pressed': string;
  '$button-color-muted-primary-label': string;
  '$button-color-muted-primary-label-hover': string;
  '$button-color-muted-primary-label-pressed': string;
  '$button-color-muted-primary-disabled-label': string;
  '$button-color-muted-primary-disabled-border': string;
  '$button-color-muted-primary-disabled-background': string;
  '$button-color-muted-secondary-shadow': string;
  '$button-color-muted-secondary-background': string;
  '$button-color-muted-secondary-background-hover': string;
  '$button-color-muted-secondary-background-pressed': string;
  '$button-color-muted-secondary-border': string;
  '$button-color-muted-secondary-border-hover': string;
  '$button-color-muted-secondary-border-pressed': string;
  '$button-color-muted-secondary-label': string;
  '$button-color-muted-secondary-label-hover': string;
  '$button-color-muted-secondary-label-pressed': string;
  '$button-color-muted-secondary-disabled-label': string;
  '$button-color-muted-secondary-disabled-border': string;
  '$button-color-muted-secondary-disabled-background': string;
  '$button-color-muted-tertiary-shadow': string;
  '$button-color-muted-tertiary-background': string;
  '$button-color-muted-tertiary-background-hover': string;
  '$button-color-muted-tertiary-background-pressed': string;
  '$button-color-muted-tertiary-border': string;
  '$button-color-muted-tertiary-border-hover': string;
  '$button-color-muted-tertiary-border-pressed': string;
  '$button-color-muted-tertiary-label': string;
  '$button-color-muted-tertiary-label-hover': string;
  '$button-color-muted-tertiary-label-pressed': string;
  '$button-color-muted-tertiary-disabled-label': string;
  '$button-color-muted-tertiary-disabled-border': string;
  '$button-color-muted-tertiary-disabled-background': string;
  '$button-color-success-primary-shadow': string;
  '$button-color-success-primary-background': string;
  '$button-color-success-primary-background-hover': string;
  '$button-color-success-primary-background-pressed': string;
  '$button-color-success-primary-border': string;
  '$button-color-success-primary-border-hover': string;
  '$button-color-success-primary-border-pressed': string;
  '$button-color-success-primary-label': string;
  '$button-color-success-primary-label-hover': string;
  '$button-color-success-primary-label-pressed': string;
  '$button-color-success-primary-disabled-label': string;
  '$button-color-success-primary-disabled-border': string;
  '$button-color-success-primary-disabled-background': string;
  '$button-color-success-secondary-shadow': string;
  '$button-color-success-secondary-background': string;
  '$button-color-success-secondary-background-hover': string;
  '$button-color-success-secondary-background-pressed': string;
  '$button-color-success-secondary-border': string;
  '$button-color-success-secondary-border-hover': string;
  '$button-color-success-secondary-border-pressed': string;
  '$button-color-success-secondary-label': string;
  '$button-color-success-secondary-label-hover': string;
  '$button-color-success-secondary-label-pressed': string;
  '$button-color-success-secondary-disabled-label': string;
  '$button-color-success-secondary-disabled-border': string;
  '$button-color-success-secondary-disabled-background': string;
  '$button-color-success-tertiary-shadow': string;
  '$button-color-success-tertiary-background': string;
  '$button-color-success-tertiary-background-hover': string;
  '$button-color-success-tertiary-background-pressed': string;
  '$button-color-success-tertiary-border': string;
  '$button-color-success-tertiary-border-hover': string;
  '$button-color-success-tertiary-border-pressed': string;
  '$button-color-success-tertiary-label': string;
  '$button-color-success-tertiary-label-hover': string;
  '$button-color-success-tertiary-label-pressed': string;
  '$button-color-success-tertiary-disabled-label': string;
  '$button-color-success-tertiary-disabled-border': string;
  '$button-color-success-tertiary-disabled-background': string;
  '$button-color-warning-primary-shadow': string;
  '$button-color-warning-primary-background': string;
  '$button-color-warning-primary-background-hover': string;
  '$button-color-warning-primary-background-pressed': string;
  '$button-color-warning-primary-border': string;
  '$button-color-warning-primary-border-hover': string;
  '$button-color-warning-primary-border-pressed': string;
  '$button-color-warning-primary-label': string;
  '$button-color-warning-primary-label-hover': string;
  '$button-color-warning-primary-label-pressed': string;
  '$button-color-warning-primary-disabled-label': string;
  '$button-color-warning-primary-disabled-border': string;
  '$button-color-warning-primary-disabled-background': string;
  '$button-color-warning-secondary-shadow': string;
  '$button-color-warning-secondary-background': string;
  '$button-color-warning-secondary-background-hover': string;
  '$button-color-warning-secondary-background-pressed': string;
  '$button-color-warning-secondary-border': string;
  '$button-color-warning-secondary-border-hover': string;
  '$button-color-warning-secondary-border-pressed': string;
  '$button-color-warning-secondary-label': string;
  '$button-color-warning-secondary-label-hover': string;
  '$button-color-warning-secondary-label-pressed': string;
  '$button-color-warning-secondary-disabled-label': string;
  '$button-color-warning-secondary-disabled-border': string;
  '$button-color-warning-secondary-disabled-background': string;
  '$button-color-warning-tertiary-shadow': string;
  '$button-color-warning-tertiary-background': string;
  '$button-color-warning-tertiary-background-hover': string;
  '$button-color-warning-tertiary-background-pressed': string;
  '$button-color-warning-tertiary-border': string;
  '$button-color-warning-tertiary-border-hover': string;
  '$button-color-warning-tertiary-border-pressed': string;
  '$button-color-warning-tertiary-label': string;
  '$button-color-warning-tertiary-label-hover': string;
  '$button-color-warning-tertiary-label-pressed': string;
  '$button-color-warning-tertiary-disabled-label': string;
  '$button-color-warning-tertiary-disabled-border': string;
  '$button-color-warning-tertiary-disabled-background': string;
  '$button-color-critical-primary-shadow': string;
  '$button-color-critical-primary-background': string;
  '$button-color-critical-primary-background-hover': string;
  '$button-color-critical-primary-background-pressed': string;
  '$button-color-critical-primary-border': string;
  '$button-color-critical-primary-border-hover': string;
  '$button-color-critical-primary-border-pressed': string;
  '$button-color-critical-primary-label': string;
  '$button-color-critical-primary-label-hover': string;
  '$button-color-critical-primary-label-pressed': string;
  '$button-color-critical-primary-disabled-label': string;
  '$button-color-critical-primary-disabled-border': string;
  '$button-color-critical-primary-disabled-background': string;
  '$button-color-critical-secondary-shadow': string;
  '$button-color-critical-secondary-background': string;
  '$button-color-critical-secondary-background-hover': string;
  '$button-color-critical-secondary-background-pressed': string;
  '$button-color-critical-secondary-border': string;
  '$button-color-critical-secondary-border-hover': string;
  '$button-color-critical-secondary-border-pressed': string;
  '$button-color-critical-secondary-label': string;
  '$button-color-critical-secondary-label-hover': string;
  '$button-color-critical-secondary-label-pressed': string;
  '$button-color-critical-secondary-disabled-label': string;
  '$button-color-critical-secondary-disabled-border': string;
  '$button-color-critical-secondary-disabled-background': string;
  '$button-color-critical-tertiary-shadow': string;
  '$button-color-critical-tertiary-background': string;
  '$button-color-critical-tertiary-background-hover': string;
  '$button-color-critical-tertiary-background-pressed': string;
  '$button-color-critical-tertiary-border': string;
  '$button-color-critical-tertiary-border-hover': string;
  '$button-color-critical-tertiary-border-pressed': string;
  '$button-color-critical-tertiary-label': string;
  '$button-color-critical-tertiary-label-hover': string;
  '$button-color-critical-tertiary-label-pressed': string;
  '$button-color-critical-tertiary-disabled-label': string;
  '$button-color-critical-tertiary-disabled-border': string;
  '$button-color-critical-tertiary-disabled-background': string;
  '$button-color-info-primary-shadow': string;
  '$button-color-info-primary-background': string;
  '$button-color-info-primary-background-hover': string;
  '$button-color-info-primary-background-pressed': string;
  '$button-color-info-primary-border': string;
  '$button-color-info-primary-border-hover': string;
  '$button-color-info-primary-border-pressed': string;
  '$button-color-info-primary-label': string;
  '$button-color-info-primary-label-hover': string;
  '$button-color-info-primary-label-pressed': string;
  '$button-color-info-primary-disabled-label': string;
  '$button-color-info-primary-disabled-border': string;
  '$button-color-info-primary-disabled-background': string;
  '$button-color-info-secondary-shadow': string;
  '$button-color-info-secondary-background': string;
  '$button-color-info-secondary-background-hover': string;
  '$button-color-info-secondary-background-pressed': string;
  '$button-color-info-secondary-border': string;
  '$button-color-info-secondary-border-hover': string;
  '$button-color-info-secondary-border-pressed': string;
  '$button-color-info-secondary-label': string;
  '$button-color-info-secondary-label-hover': string;
  '$button-color-info-secondary-label-pressed': string;
  '$button-color-info-secondary-disabled-label': string;
  '$button-color-info-secondary-disabled-border': string;
  '$button-color-info-secondary-disabled-background': string;
  '$button-color-info-tertiary-shadow': string;
  '$button-color-info-tertiary-background': string;
  '$button-color-info-tertiary-background-hover': string;
  '$button-color-info-tertiary-background-pressed': string;
  '$button-color-info-tertiary-border': string;
  '$button-color-info-tertiary-border-hover': string;
  '$button-color-info-tertiary-border-pressed': string;
  '$button-color-info-tertiary-label': string;
  '$button-color-info-tertiary-label-hover': string;
  '$button-color-info-tertiary-label-pressed': string;
  '$button-color-info-tertiary-disabled-label': string;
  '$button-color-info-tertiary-disabled-border': string;
  '$button-color-info-tertiary-disabled-background': string;
}
interface Children {
}

const dataObj: RootObject = {
  "0": "@import \"../base-tokens/color-token.scss\";",
  "1": "@import \"../base-tokens/shadow-token.scss\";",
  "2": "@import \"../base-tokens/typography-token.scss\";",
  "children": {},
  "attributes": {
    "$button-color-prime-primary-shadow": "#c74900",
    "$button-color-prime-primary-background": "#c74900",
    "$button-color-prime-primary-background-hover": "#9e4100",
    "$button-color-prime-primary-background-pressed": "#873b00",
    "$button-color-prime-primary-border": "none",
    "$button-color-prime-primary-border-hover": "none",
    "$button-color-prime-primary-border-pressed": "none",
    "$button-color-prime-primary-label": "#ffffff",
    "$button-color-prime-primary-label-hover": "#ffffff",
    "$button-color-prime-primary-label-pressed": "#ffffff",
    "$button-color-prime-primary-disabled-label": "#ffffff",
    "$button-color-prime-primary-disabled-border": "none",
    "$button-color-prime-primary-disabled-background": "#9997aa",
    "$button-color-prime-secondary-shadow": "#c74900",
    "$button-color-prime-secondary-background": "none",
    "$button-color-prime-secondary-background-hover": "#fff8f5",
    "$button-color-prime-secondary-background-pressed": "#fee2d6",
    "$button-color-prime-secondary-border": "#c74900",
    "$button-color-prime-secondary-border-hover": "#9e4100",
    "$button-color-prime-secondary-border-pressed": "#873b00",
    "$button-color-prime-secondary-label": "#c74900",
    "$button-color-prime-secondary-label-hover": "#9e4100",
    "$button-color-prime-secondary-label-pressed": "#873b00",
    "$button-color-prime-secondary-disabled-label": "#9997aa",
    "$button-color-prime-secondary-disabled-border": "#ececf3",
    "$button-color-prime-secondary-disabled-background": "none",
    "$button-color-prime-tertiary-shadow": "#c74900",
    "$button-color-prime-tertiary-background": "none",
    "$button-color-prime-tertiary-background-hover": "#fff8f5",
    "$button-color-prime-tertiary-background-pressed": "#fee2d6",
    "$button-color-prime-tertiary-border": "none",
    "$button-color-prime-tertiary-border-hover": "none",
    "$button-color-prime-tertiary-border-pressed": "none",
    "$button-color-prime-tertiary-label": "#c74900",
    "$button-color-prime-tertiary-label-hover": "#9e4100",
    "$button-color-prime-tertiary-label-pressed": "#873b00",
    "$button-color-prime-tertiary-disabled-label": "#9997aa",
    "$button-color-prime-tertiary-disabled-border": "none",
    "$button-color-prime-tertiary-disabled-background": "none",
    "$button-color-muted-primary-shadow": "#3d3c52",
    "$button-color-muted-primary-background": "#3d3c52",
    "$button-color-muted-primary-background-hover": "#2b2b40",
    "$button-color-muted-primary-background-pressed": "#1f1f32",
    "$button-color-muted-primary-border": "none",
    "$button-color-muted-primary-border-hover": "none",
    "$button-color-muted-primary-border-pressed": "none",
    "$button-color-muted-primary-label": "#ffffff",
    "$button-color-muted-primary-label-hover": "#ffffff",
    "$button-color-muted-primary-label-pressed": "#ffffff",
    "$button-color-muted-primary-disabled-label": "#ffffff",
    "$button-color-muted-primary-disabled-border": "none",
    "$button-color-muted-primary-disabled-background": "#9997aa",
    "$button-color-muted-secondary-shadow": "#3d3c52",
    "$button-color-muted-secondary-background": "none",
    "$button-color-muted-secondary-background-hover": "#f6f6f9",
    "$button-color-muted-secondary-background-pressed": "#f2f2f8",
    "$button-color-muted-secondary-border": "#dfdde7",
    "$button-color-muted-secondary-border-hover": "#c0becc",
    "$button-color-muted-secondary-border-pressed": "#9997aa",
    "$button-color-muted-secondary-label": "#3d3c52",
    "$button-color-muted-secondary-label-hover": "#2b2b40",
    "$button-color-muted-secondary-label-pressed": "#1f1f32",
    "$button-color-muted-secondary-disabled-label": "#9997aa",
    "$button-color-muted-secondary-disabled-border": "#ececf3",
    "$button-color-muted-secondary-disabled-background": "none",
    "$button-color-muted-tertiary-shadow": "#3d3c52",
    "$button-color-muted-tertiary-background": "none",
    "$button-color-muted-tertiary-background-hover": "#f6f6f9",
    "$button-color-muted-tertiary-background-pressed": "#f2f2f8",
    "$button-color-muted-tertiary-border": "none",
    "$button-color-muted-tertiary-border-hover": "none",
    "$button-color-muted-tertiary-border-pressed": "none",
    "$button-color-muted-tertiary-label": "#3d3c52",
    "$button-color-muted-tertiary-label-hover": "#2b2b40",
    "$button-color-muted-tertiary-label-pressed": "#1f1f32",
    "$button-color-muted-tertiary-disabled-label": "#9997aa",
    "$button-color-muted-tertiary-disabled-border": "none",
    "$button-color-muted-tertiary-disabled-background": "none",
    "$button-color-success-primary-shadow": "#198558",
    "$button-color-success-primary-background": "#198558",
    "$button-color-success-primary-background-hover": "#106a40",
    "$button-color-success-primary-background-pressed": "#0c5532",
    "$button-color-success-primary-border": "none",
    "$button-color-success-primary-border-hover": "none",
    "$button-color-success-primary-border-pressed": "none",
    "$button-color-success-primary-label": "#ffffff",
    "$button-color-success-primary-label-hover": "#ffffff",
    "$button-color-success-primary-label-pressed": "#ffffff",
    "$button-color-success-primary-disabled-label": "#ffffff",
    "$button-color-success-primary-disabled-border": "none",
    "$button-color-success-primary-disabled-background": "#9997aa",
    "$button-color-success-secondary-shadow": "#198558",
    "$button-color-success-secondary-background": "none",
    "$button-color-success-secondary-background-hover": "#f1fef9",
    "$button-color-success-secondary-background-pressed": "#d9fbee",
    "$button-color-success-secondary-border": "#198558",
    "$button-color-success-secondary-border-hover": "#106a40",
    "$button-color-success-secondary-border-pressed": "#0c5532",
    "$button-color-success-secondary-label": "#198558",
    "$button-color-success-secondary-label-hover": "#106a40",
    "$button-color-success-secondary-label-pressed": "#0c5532",
    "$button-color-success-secondary-disabled-label": "#9997aa",
    "$button-color-success-secondary-disabled-border": "#ececf3",
    "$button-color-success-secondary-disabled-background": "none",
    "$button-color-success-tertiary-shadow": "#198558",
    "$button-color-success-tertiary-background": "none",
    "$button-color-success-tertiary-background-hover": "#f1fef9",
    "$button-color-success-tertiary-background-pressed": "#d9fbee",
    "$button-color-success-tertiary-border": "none",
    "$button-color-success-tertiary-border-hover": "none",
    "$button-color-success-tertiary-border-pressed": "none",
    "$button-color-success-tertiary-label": "#198558",
    "$button-color-success-tertiary-label-hover": "#106a40",
    "$button-color-success-tertiary-label-pressed": "#0c5532",
    "$button-color-success-tertiary-disabled-label": "#9997aa",
    "$button-color-success-tertiary-disabled-border": "none",
    "$button-color-success-tertiary-disabled-background": "none",
    "$button-color-warning-primary-shadow": "#f4b31a",
    "$button-color-warning-primary-background": "#f4b31a",
    "$button-color-warning-primary-background-hover": "#e0a400",
    "$button-color-warning-primary-background-pressed": "#ad7900",
    "$button-color-warning-primary-border": "none",
    "$button-color-warning-primary-border-hover": "none",
    "$button-color-warning-primary-border-pressed": "none",
    "$button-color-warning-primary-label": "#1f1f32",
    "$button-color-warning-primary-label-hover": "#1f1f32",
    "$button-color-warning-primary-label-pressed": "#1f1f32",
    "$button-color-warning-primary-disabled-label": "#ffffff",
    "$button-color-warning-primary-disabled-border": "none",
    "$button-color-warning-primary-disabled-background": "#9997aa",
    "$button-color-warning-secondary-shadow": "#f4b31a",
    "$button-color-warning-secondary-background": "none",
    "$button-color-warning-secondary-background-hover": "#fefbeb",
    "$button-color-warning-secondary-background-pressed": "#fef7d6",
    "$button-color-warning-secondary-border": "#976c07",
    "$button-color-warning-secondary-border-hover": "#724f04",
    "$button-color-warning-secondary-border-pressed": "#724f04",
    "$button-color-warning-secondary-label": "#976c07",
    "$button-color-warning-secondary-label-hover": "#724f04",
    "$button-color-warning-secondary-label-pressed": "#724f04",
    "$button-color-warning-secondary-disabled-label": "#9997aa",
    "$button-color-warning-secondary-disabled-border": "#ececf3",
    "$button-color-warning-secondary-disabled-background": "none",
    "$button-color-warning-tertiary-shadow": "#f4b31a",
    "$button-color-warning-tertiary-background": "none",
    "$button-color-warning-tertiary-background-hover": "#fefbeb",
    "$button-color-warning-tertiary-background-pressed": "#fef7d6",
    "$button-color-warning-tertiary-border": "none",
    "$button-color-warning-tertiary-border-hover": "none",
    "$button-color-warning-tertiary-border-pressed": "none",
    "$button-color-warning-tertiary-label": "#976c07",
    "$button-color-warning-tertiary-label-hover": "#724f04",
    "$button-color-warning-tertiary-label-pressed": "#724f04",
    "$button-color-warning-tertiary-disabled-label": "#9997aa",
    "$button-color-warning-tertiary-disabled-border": "none",
    "$button-color-warning-tertiary-disabled-background": "none",
    "$button-color-critical-primary-shadow": "#b3141d",
    "$button-color-critical-primary-background": "#b3141d",
    "$button-color-critical-primary-background-hover": "#8e1014",
    "$button-color-critical-primary-background-pressed": "#750a0a",
    "$button-color-critical-primary-border": "none",
    "$button-color-critical-primary-border-hover": "none",
    "$button-color-critical-primary-border-pressed": "none",
    "$button-color-critical-primary-label": "#ffffff",
    "$button-color-critical-primary-label-hover": "#ffffff",
    "$button-color-critical-primary-label-pressed": "#ffffff",
    "$button-color-critical-primary-disabled-label": "#ffffff",
    "$button-color-critical-primary-disabled-border": "none",
    "$button-color-critical-primary-disabled-background": "#9997aa",
    "$button-color-critical-secondary-shadow": "#b3141d",
    "$button-color-critical-secondary-background": "none",
    "$button-color-critical-secondary-background-hover": "#fff0f3",
    "$button-color-critical-secondary-background-pressed": "#fed6dd",
    "$button-color-critical-secondary-border": "#b3141d",
    "$button-color-critical-secondary-border-hover": "#8e1014",
    "$button-color-critical-secondary-border-pressed": "#750a0a",
    "$button-color-critical-secondary-label": "#b3141d",
    "$button-color-critical-secondary-label-hover": "#8e1014",
    "$button-color-critical-secondary-label-pressed": "#750a0a",
    "$button-color-critical-secondary-disabled-label": "#9997aa",
    "$button-color-critical-secondary-disabled-border": "#ececf3",
    "$button-color-critical-secondary-disabled-background": "none",
    "$button-color-critical-tertiary-shadow": "#b3141d",
    "$button-color-critical-tertiary-background": "none",
    "$button-color-critical-tertiary-background-hover": "#fff0f3",
    "$button-color-critical-tertiary-background-pressed": "#fed6dd",
    "$button-color-critical-tertiary-border": "none",
    "$button-color-critical-tertiary-border-hover": "none",
    "$button-color-critical-tertiary-border-pressed": "none",
    "$button-color-critical-tertiary-label": "#b3141d",
    "$button-color-critical-tertiary-label-hover": "#8e1014",
    "$button-color-critical-tertiary-label-pressed": "#750a0a",
    "$button-color-critical-tertiary-disabled-label": "#9997aa",
    "$button-color-critical-tertiary-disabled-border": "none",
    "$button-color-critical-tertiary-disabled-background": "none",
    "$button-color-info-primary-shadow": "#0975d7",
    "$button-color-info-primary-background": "#0975d7",
    "$button-color-info-primary-background-hover": "#0d59ab",
    "$button-color-info-primary-background-pressed": "#033d84",
    "$button-color-info-primary-border": "none",
    "$button-color-info-primary-border-hover": "none",
    "$button-color-info-primary-border-pressed": "none",
    "$button-color-info-primary-label": "#ffffff",
    "$button-color-info-primary-label-hover": "#ffffff",
    "$button-color-info-primary-label-pressed": "#ffffff",
    "$button-color-info-primary-disabled-label": "#ffffff",
    "$button-color-info-primary-disabled-border": "none",
    "$button-color-info-primary-disabled-background": "#9997aa",
    "$button-color-info-secondary-shadow": "#0975d7",
    "$button-color-info-secondary-background": "none",
    "$button-color-info-secondary-background-hover": "#f0f9ff",
    "$button-color-info-secondary-background-pressed": "#d7effe",
    "$button-color-info-secondary-border": "#0975d7",
    "$button-color-info-secondary-border-hover": "#0d59ab",
    "$button-color-info-secondary-border-pressed": "#033d84",
    "$button-color-info-secondary-label": "#0975d7",
    "$button-color-info-secondary-label-hover": "#0d59ab",
    "$button-color-info-secondary-label-pressed": "#033d84",
    "$button-color-info-secondary-disabled-label": "#9997aa",
    "$button-color-info-secondary-disabled-border": "#ececf3",
    "$button-color-info-secondary-disabled-background": "none",
    "$button-color-info-tertiary-shadow": "#0975d7",
    "$button-color-info-tertiary-background": "none",
    "$button-color-info-tertiary-background-hover": "#f0f9ff",
    "$button-color-info-tertiary-background-pressed": "#d7effe",
    "$button-color-info-tertiary-border": "none",
    "$button-color-info-tertiary-border-hover": "none",
    "$button-color-info-tertiary-border-pressed": "none",
    "$button-color-info-tertiary-label": "#0975d7",
    "$button-color-info-tertiary-label-hover": "#0d59ab",
    "$button-color-info-tertiary-label-pressed": "#033d84",
    "$button-color-info-tertiary-disabled-label": "#9997aa",
    "$button-color-info-tertiary-disabled-border": "none",
    "$button-color-info-tertiary-disabled-background": "none"
  }
};

export default dataObj;
  
  